# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Travels through grey nothingness
email: knbknb00@yahoo.com
description: >- # this means to ignore newlines until "baseurl:"
    Musings about my personal interests:  geosciences, datasciences, 
    coding, photography, and more.
#baseurl: /blog
# the base hostname & protocol for your site, e.g. http://example.com
url: https://knbknb.github.io
twitter_username: sudo_f
github_username:  knbknb
google_analytics: true
disqus_shortname: knbghio.disqus.com
permalink: /blog/:title
# Build settings
markdown: kramdown
theme: minima
comments: true #disqus
plugins:
  - jekyll-feed
exclude: [R, knbknb.github.io.Rproj]
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
